#!/bin/sh

logger button $BUTTON was $ACTION

[ "$BUTTON" != "BTN_0"] && exit 0

case "$ACTION" in
	pressed)
		/etc/scripts/set_inet_restriction on
		;;
	released)
		/etc/scripts/set_inet_restriction off
		;;
esac
